name: Push Tags

on:
  push:
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Since you mentioned GIT_STRATEGY: none, implying you don't need the source.
        # However, to interact with Docker, we typically need to checkout the code.
        # If you really do not need the code, you might not need this step at all.
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        # Assuming you are using GitHub Container Registry; change these to match your registry.
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Docker Image
      run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Tag Docker Image
      run: docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:${{ github.event.ref }}

    - name: Push Docker Image
      run: docker push ghcr.io/${{ github.repository }}:${{ github.event.ref }}
